// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Report = __t.object("Report", {
  id: __t.u64(),
  spotId: __t.u64(),
  reporter: __t.identity(),
  status: __t.string(),
  note: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Report = __Infer<typeof Report>;

export const Spot = __t.object("Spot", {
  id: __t.u64(),
  name: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  category: __t.string(),
});
export type Spot = __Infer<typeof Spot>;

export const User = __t.object("User", {
  identity: __t.identity(),
  handle: __t.string(),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

