// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import SetHandleReducer from "../set_handle_reducer";
import SubmitReportReducer from "../submit_report_reducer";

export type SetHandleParams = __Infer<typeof SetHandleReducer>;
export type SubmitReportParams = __Infer<typeof SubmitReportReducer>;

